name: "Universal Changelog Generator"
description: "Unopinionated changelog for your conventional commits. Doesn't force you to use semver or any specific versioning strategy."
author: "Hrusikesh Panda <mrchief_2000@yahoo.com>"
branding:
  icon: "book"
  color: "blue"
inputs:
  commits:
    description: "List of Commits (https://developer.github.com/v3/repos/commits/#list-commits)"
  previousReleaseTagNameOrSha:
    description: "Tag Name or Sha of latest release"
  nextReleaseTagName:
    description: "Tag Name of next release"
  nextReleaseName:
    description: "Friendly Name of next release"
outputs:
  changelog:
    description: "Changelog in markdown format"
runs:
  using: "node12"
  main: "dist/index.js"
